### ISSUE TITLE
Usage help should be displayed if no argument given

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm-client#3]
Currently it displays an error
```
$ zimfarm 
Traceback (most recent call last):
  File "/usr/local/bin/zimfarm", line 11, in <module>
    load_entry_point('zimfarm==0.0.10', 'console_scripts', 'zimfarm')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/zimfarm/commands/__init__.py", line 3, in <module>
    from . import login, logout
  File "/usr/local/lib/python2.7/dist-packages/zimfarm/commands/login.py", line 9
    def register(parser: ArgumentParser):
                       ^
SyntaxError: invalid syntax
```

**Comment by kelson42** [comment]
same if I call `zimfarm login user password`, it might be that this is quite unclear which version of python should be used pip2/pip3 and python2/python3?

**Comment by automactic** [comment]
@kelson42 from what I can see, you are using an older version of python. You need 3.7.

running `zimfarm` command on a compatible version of python does not show help message, so this issue should remain open for now.

**Comment by kelson42** [comment]
@automactic python2 is the std version of Ubuntu 18.04. I think we should just update the documentation (use pip3 instead of pip2) and implement the usage properly

**Comment by automactic** [comment]
@kelson42 No, if you are inside a python3 virtualenv, `pip` is linked to `pip3`. But really, I think specifying python version itself is enough. (I mean, no one would use pip2 to install a python3 only package anyway)
